# Generated by Django 5.0.2 on 2024-02-19 05:16

import django.db.models.deletion
import django.utils.timezone
import email_generator.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FlaconAIUser",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("is_admin", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
            managers=[
                ("objects", email_generator.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "business_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Campaign",
            fields=[
                (
                    "campaign_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("start_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("end_date", models.DateTimeField()),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_generator.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "employee_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=255, unique=True, verbose_name="email address"
                    ),
                ),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_generator.business",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AIEmail",
            fields=[
                (
                    "email_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                ("email_topic", models.CharField(max_length=500, null=True)),
                (
                    "writing_style",
                    models.IntegerField(
                        choices=[
                            (0, "Formal"),
                            (1, "Appreciating"),
                            (2, "Not Satisfied"),
                            (3, "Neutral"),
                        ],
                        default=0,
                        null=True,
                        verbose_name="writing style",
                    ),
                ),
                ("email_content", models.TextField()),
                (
                    "sender",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_generator.campaign",
                    ),
                ),
                (
                    "recipient",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="email_generator.employee",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EmployeeAction",
            fields=[
                (
                    "action_id",
                    models.CharField(max_length=100, primary_key=True, serialize=False),
                ),
                (
                    "action",
                    models.IntegerField(
                        choices=[(0, "Click"), (1, "View")],
                        default=0,
                        null=True,
                        verbose_name="action",
                    ),
                ),
                (
                    "email",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_generator.aiemail",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="email_generator.employee",
                    ),
                ),
            ],
        ),
    ]
