# Generated by Django 3.1.6 on 2024-02-19 01:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('email_generator', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aiemail',
            name='campaign',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_generator.campaign'),
        ),
        migrations.AlterField(
            model_name='aiemail',
            name='email_topic',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='aiemail',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='email_generator.employee'),
        ),
        migrations.AlterField(
            model_name='aiemail',
            name='sender',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='aiemail',
            name='writing_style',
            field=models.IntegerField(choices=[(0, 'Formal'), (1, 'Appreciating'), (2, 'Not Satisfied'), (3, 'Neutral')], default=0, null=True, verbose_name='writing style'),
        ),
        migrations.CreateModel(
            name='EmployeeAction',
            fields=[
                ('action_id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('action', models.IntegerField(choices=[(0, 'Click'), (1, 'View')], default=0, null=True, verbose_name='action')),
                ('email', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_generator.aiemail')),
                ('employee', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='email_generator.employee')),
            ],
        ),
    ]
